# Generated by Django 4.1 on 2022-08-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('isCollaborative', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('url', models.URLField(default='')),
            ],
        ),
    ]
