# Generated by Django 4.1 on 2022-08-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_app', '0002_alter_playlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='owner',
            field=models.CharField(max_length=255),
        ),
    ]
